### ISSUE TITLE
Commands Not Found

### ISSUE THREAD

**Issue by PealyOJ** [circumspect/White-Rabbit#123]
**Description**
When using any of the commands in the bot channel, the Bot replies "Command not found!".
I saw the previous issue report regarding "MESSAGE CONTENT INTENT" setting on Discord Developer portal when setting up the bot, but this is enabled.

**Reproducing**
Commands tried:
!init
!reset
!help
!wipe

**Expected behavior**
Commands to be found and if not able to be implemented some kind of error as to why.

**System Info**
OS:  Windows 10
Python version: 3.11
Bot version: 0.12.2

**Other details**
-

**Comment by circumspect** [comment]
Do you have all of the intents enabled in the Discord developer portal?

**Comment by PealyOJ** [comment]
> Also, have you looked at [this](https://github.com/circumspect/White-Rabbit/issues/109)? You might have discord.py v2 installed - try running `pip install -r requirements.txt`

This did it!

For reference, I was tripped up initially by the guide, as the Windows command for Python is "py" not "Python", which is in your guide - can I suggest that is added for clarity?

**Comment by circumspect** [comment]
Hi,
The Windows command to run Python is still `python` - note that `py` is the Python launcher, which 1. may or may not be installed on the user's computer, and 2. exists only on Windows. I myself was unaware that the launcher even existed until today.

My personal opinion is that writing `python` is enough, and that knowing/looking up how to run a Python script is the user's responsibility. For example, most Linux systems I've encountered use `python3` to launch Python 3.x, but that information is also omitted from the documentation, as the documentation focuses on how to use the bot, rather than the details of using Python.
